version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartru-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smartru_db}
      POSTGRES_USER: ${POSTGRES_USER:-smartru_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smartru_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartru-network

  app:
    build: .
    container_name: smartru-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-smartru_db}
      POSTGRES_USER: ${POSTGRES_USER:-smartru_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smartru_password}
      APP_ENV: ${APP_ENV:-development}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - smartru-network

volumes:
  postgres_data:


networks:
  smartru-network:
    driver: bridge
